version: 0.2

env:
  variables:
    GOOS: "linux"
    GOARCH: "amd64"

phases:
  install:
    runtime-versions:
      golang: latest
      nodejs: latest
    commands:
      - npm install -g yarn
  build:
    commands:
      - echo "Building Go..."
      - cd $CODEBUILD_SRC_DIR/src
      - go build -mod vendor -ldflags "-X github.com/eynorey/solarflare/src/config.appVersion=$(date -u '+%Y-%m-%d-%H:%M')" -o ../bin/application -i github.com/eynorey/solarflare/src
      - chmod 755 ../bin/application
      - echo "Building React..."
      - cd $CODEBUILD_SRC_DIR/client
      - yarn
      - yarn build
      - mv build ../public
artifacts:
  files:
    - .ebextensions/*
    - bin/application
    - public/**/*
