import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faPlusCircle,
    faChevronDown,
    faQuoteLeft,
    faQuoteRight,
    faWindowClose,
    faSave,
    faBars,
    faArrowLeft,
    faCogs,
    faVial,
    faStepForward,
    faPalette,
    faSync,
    faPlay,
    faStop,
    faQuestion,
    faStopCircle as fasStopCircle,
    faStopwatch,
    faEye,
    faSatelliteDish,
    faGlobeAsia,
    faSquare as fasFaSquare,
    faSkull,
    faPaperPlane,
    faTachometerAlt,
    faTerminal
} from "@fortawesome/free-solid-svg-icons";

import {
    faEdit,
    faClone,
    faTrashAlt,
    faListAlt,
    faStopCircle as farStopCircle,
    faSquare as farFaSquare,
    faEyeSlash
} from "@fortawesome/free-regular-svg-icons";

library.add(
    faPlusCircle,
    faChevronDown,
    faQuoteLeft,
    faQuoteRight,
    faWindowClose,
    faSave,
    faBars,
    faArrowLeft,
    faCogs,
    faVial,
    faStepForward,
    faPalette,
    faSync,
    faPlay,
    faStop,
    faQuestion,
    fasStopCircle,
    faStopwatch,
    faEye,
    faSatelliteDish,
    faGlobeAsia,
    fasFaSquare,
    faSkull,
    faPaperPlane,
    faTachometerAlt,
    faTerminal,

    faEdit,
    faClone,
    faTrashAlt,
    faListAlt,
    farStopCircle,
    farFaSquare,
    faEyeSlash
);
